from __future__ import annotations

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from utils.logger import setup_logger


class EmailDeliverer:
    def __init__(self, host: str, port: int, user: str, password: str, to_addr: str):
        self.host = host
        self.port = port
        self.user = user
        self.password = password
        self.to_addr = to_addr
        self.logger = setup_logger("EmailDeliverer")

    def send(self, subject: str, html_content: str) -> bool:
        if not all([self.host, self.user, self.password, self.to_addr]):
            self.logger.warning("Email not configured, skipping")
            return False

        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = self.user
            msg["To"] = self.to_addr

            html_body = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 700px; margin: 0 auto; padding: 20px; }}
                    h1 {{ color: #1a1a1a; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }}
                    h2 {{ color: #4f46e5; margin-top: 30px; }}
                    h3 {{ color: #374151; }}
                    a {{ color: #4f46e5; }}
                    blockquote {{ border-left: 3px solid #4f46e5; margin: 10px 0; padding: 10px 15px; background: #f9fafb; }}
                    ul {{ padding-left: 20px; }}
                    li {{ margin: 8px 0; }}
                    .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; }}
                </style>
            </head>
            <body>
                {html_content}
                <div class="footer">
                    <p>Generated by Daily AI & Tech Intelligence Agent</p>
                </div>
            </body>
            </html>
            """

            msg.attach(MIMEText(html_body, "html"))

            if self.port == 465:
                with smtplib.SMTP_SSL(self.host, self.port) as server:
                    server.login(self.user, self.password)
                    server.send_message(msg)
            else:
                with smtplib.SMTP(self.host, self.port) as server:
                    server.starttls()
                    server.login(self.user, self.password)
                    server.send_message(msg)

            self.logger.info(f"Email sent to {self.to_addr}")
            return True
        except Exception as e:
            self.logger.error(f"Email delivery failed: {e}")
            return False
